name: Auto Version and Tag

on:
  workflow_call:
  workflow_dispatch:

jobs:
  auto-version-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      published: ${{ steps.semantic-release.outputs.new_release_published }}
      version:   ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Semantic release (version, tag, GitHub release)
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    needs: auto-version-and-release
    if: needs.auto-version-and-release.outputs.published == 'true'
    uses: ./.github/workflows/docker-tags.yml
    with:
      tag: ${{ needs.auto-version-and-release.outputs.version }}
    secrets: inherit
