name: Docker (Feature Branch)

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg="COMMIT_SHA=${{ github.sha }}"\
            --build-arg="IMAGE_VERSION=${{ github.sha }}-stella-test" \
            -t ghcr.io/${{ github.repository }}:${{ github.sha }}-stella-test .
